<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Admin-登陆</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="format-detection" content="telephone=no">
    <link rel="stylesheet" href="/assert/admin/lib/layui-v2.6.3/css/layui.css" media="all">
    <style>
        body {background-image:url("/assert/admin/images/bg.jpg");height:100%;width:100%;}
        #container{height:100%;width:100%;}
        input:-webkit-autofill {-webkit-box-shadow:inset 0 0 0 1000px #fff;background-color:transparent;}
        .admin-login-background {width:300px;height:300px;position:absolute;left:50%;top:40%;margin-left:-150px;margin-top:-100px;}
        .admin-header {text-align:center;margin-bottom:20px;color:#ffffff;font-weight:bold;font-size:40px}
        .admin-input {border-top-style:none;border-right-style:solid;border-bottom-style:solid;border-left-style:solid;height:50px;width:300px;padding-bottom:0px;}
        .admin-input::-webkit-input-placeholder {color:#a78369}
        .layui-icon-username {color:#a78369 !important;}
        .layui-icon-username:hover {color:#9dadce !important;}
        .layui-icon-password {color:#a78369 !important;}
        .password{border-radius:0 0 10px 10px;}
        .layui-icon-password:hover {color:#9dadce !important;}
        .username {border-top-style:solid;border-radius:10px 10px 0 0;}
        .admin-button {margin-top:20px;font-weight:bold;font-size:18px;width:300px;height:50px;border-radius:5px;background-color:#a78369;border:1px solid #d8b29f}
        .admin-icon {margin-left:260px;margin-top:10px;font-size:30px;}
        i {position:absolute;}
    </style>
</head>
<body>
<div id="container">
    <div></div>
    <div class="admin-login-background">
        <div class="admin-header">
            <span>Admin</span>
        </div>
        <div class="layui-form">
            <div>
                <i class="layui-icon layui-icon-username admin-icon"></i>
                <input type="text" name="username" placeholder="请输入用户名" autocomplete="off" class="layui-input admin-input username" value="">
            </div>
            <div>
                <i class="layui-icon layui-icon-password admin-icon"></i>
                <input type="password" name="password" placeholder="请输入密码" autocomplete="off" class="layui-input admin-input password" value="">
            </div>
            <button class="layui-btn admin-button btn-login" lay-submit="" lay-filter="login">登 录</button>
        </div>
    </div>
</div>
<script src="/assert/admin/lib/layui-v2.6.3/layui.js" charset="utf-8"></script>
<script src="/assert/admin/lib/jquery-3.4.1/jquery-3.4.1.min.js" charset="utf-8"></script>
<script>
    layui.use(['form'], function () {
        var form = layui.form,
            layer = layui.layer;

        $(document).keyup(function(e){
            let key = e.which;
            if(key == 13){
                $('.btn-login').click();
            }
        });

        // 进行登录操作
        form.on('submit(login)', function (data) {
            data = data.field;

            $.post('/attempt',data,function (res) {

                if (res.code != 1000){
                    layer.msg(res.info);
                }else{
                    window.location = '/index';
                }
                console.log(data);
            })

            return false;
        });
    });
</script>
</body>
</html>
