<div class="layui-side layui-bg-black layuimini-menu-left">
    <ul class="layui-nav layui-nav-tree layui-left-nav-tree layui-this slide-menu">

<!--       <li class="layui-nav-item menu-li  layui-nav-itemed ">-->
<!---->
<!--           <a target="_self" href="javascript:;">-->
<!--                <i class="fa fa-home"></i>-->
<!--                <span class="layui-left-nav">title</span>-->
<!--                <span class="layui-nav-more"></span>-->
<!--            </a>-->
<!--            <dl class="layui-nav-child">-->
<!--                <dd class="menu-dd layui-nav-itemed ">-->
<!--                    <a href="javascript:;" target="_self">-->
<!--                        <i class="fa fa-navicon"></i>-->
<!--                        <span class="layui-left-nav"> s-title</span>-->
<!--                    </a>-->
<!--                    <dl class="layui-nav-child ">-->
<!--                        <dd class="menu-dd layui-this" >-->
<!--                            <a href="javascript:;" target="_self">-->
<!--                                <i class="fa fa-navicon"></i>-->
<!--                                <span class="layui-left-nav"> t-title</span>-->
<!--                            </a>-->
<!--                        </dd>-->
<!--                    </dl>-->
<!--                </dd>-->
<!--            </dl>-->
<!--        </li>-->
    </ul>
</div>
